"""Tests for HomeKit zone server API."""

from __future__ import annotations

from types import SimpleNamespace

import pytest

try:
    from flask import Flask
    from copilot_core.api.v1 import homekit as homekit_api
    from copilot_core.hub import api as hub_api
except ModuleNotFoundError:  # pragma: no cover - environment without core deps
    Flask = None
    homekit_api = None
    hub_api = None


class _FakeZoneEngine:
    def get_overview(self):
        return SimpleNamespace(
            zones=[
                {"zone_id": "zone_wohnbereich", "name": "Wohnbereich", "enabled": True},
                {"zone_id": "zone_badbereich", "name": "Badbereich", "enabled": True},
            ]
        )

    def get_zone(self, zone_id: str):
        if zone_id == "zone_wohnbereich":
            return {
                "zone_id": zone_id,
                "name": "Wohnbereich",
                "entities": [
                    "light.retrolampe",
                    "binary_sensor.bewegung_wohnzimmer",
                    "sensor.helligkeit_wohnzimmer",
                ],
            }
        if zone_id == "zone_badbereich":
            return {
                "zone_id": zone_id,
                "name": "Badbereich",
                "entities": [
                    "light.bad_spiegel",
                    "sensor.feuchte_bad",
                    "binary_sensor.bewegung_bad",
                ],
            }
        return {}


def _build_app_with_store():
    assert Flask is not None
    app = Flask("homekit_test")
    app.register_blueprint(homekit_api.homekit_bp)
    return app


@pytest.mark.skipif(Flask is None, reason="flask not available")
def test_homekit_servers_autogenerated_from_habitus(monkeypatch, tmp_path):
    monkeypatch.setenv(
        "PILOTSUITE_HOMEKIT_SERVERS_PATH",
        str(tmp_path / "homekit_zone_servers.json"),
    )
    monkeypatch.setattr(hub_api, "_zone_engine", _FakeZoneEngine())
    homekit_api._CACHE = None
    homekit_api._RESOLVED_STORE_PATH = None

    app = _build_app_with_store()
    client = app.test_client()

    r = client.get("/api/v1/homekit/servers")
    assert r.status_code == 200
    payload = r.get_json()
    assert payload["ok"] is True
    assert payload["summary"]["total_servers"] >= 2

    by_zone = {item["zone_id"]: item for item in payload["servers"]}
    assert "zone_wohnbereich" in by_zone
    assert by_zone["zone_wohnbereich"]["entity_count"] >= 1
    assert by_zone["zone_wohnbereich"]["status"] in {"online", "degraded"}


@pytest.mark.skipif(Flask is None, reason="flask not available")
def test_homekit_toggle_and_config(monkeypatch, tmp_path):
    monkeypatch.setenv(
        "PILOTSUITE_HOMEKIT_SERVERS_PATH",
        str(tmp_path / "homekit_zone_servers.json"),
    )
    monkeypatch.setattr(hub_api, "_zone_engine", _FakeZoneEngine())
    homekit_api._CACHE = None
    homekit_api._RESOLVED_STORE_PATH = None

    app = _build_app_with_store()
    client = app.test_client()

    toggle_resp = client.post(
        "/api/v1/homekit/toggle",
        json={
            "zone_id": "zone_wohnbereich",
            "zone_name": "Wohnbereich",
            "entity_ids": ["light.retrolampe", "sensor.helligkeit_wohnzimmer"],
            "enabled": False,
        },
    )
    assert toggle_resp.status_code == 200
    toggle_payload = toggle_resp.get_json()
    assert toggle_payload["success"] is True
    assert toggle_payload["enabled"] is False

    cfg_resp = client.post(
        "/api/v1/homekit/servers/zone_wohnbereich/config",
        json={
            "display_name": "Wohnbereich by Styx",
            "enabled": True,
            "sync_entities": True,
            "include_domains": ["light", "sensor"],
        },
    )
    assert cfg_resp.status_code == 200
    cfg_payload = cfg_resp.get_json()
    assert cfg_payload["ok"] is True
    assert cfg_payload["server"]["enabled"] is True
    assert cfg_payload["server"]["display_name"] == "Wohnbereich by Styx"

    get_resp = client.get("/api/v1/homekit/servers/zone_wohnbereich")
    assert get_resp.status_code == 200
    get_payload = get_resp.get_json()
    assert get_payload["ok"] is True
    assert get_payload["server"]["display_name"] == "Wohnbereich by Styx"


@pytest.mark.skipif(Flask is None, reason="flask not available")
def test_homekit_qr_svg_endpoint(monkeypatch, tmp_path):
    monkeypatch.setenv(
        "PILOTSUITE_HOMEKIT_SERVERS_PATH",
        str(tmp_path / "homekit_zone_servers.json"),
    )
    monkeypatch.setattr(hub_api, "_zone_engine", _FakeZoneEngine())
    homekit_api._CACHE = None
    homekit_api._RESOLVED_STORE_PATH = None

    app = _build_app_with_store()
    client = app.test_client()

    # Ensure servers were generated first.
    client.get("/api/v1/homekit/servers")
    r = client.get("/api/v1/homekit/qr/zone_wohnbereich.svg")
    assert r.status_code == 200
    assert "image/svg+xml" in (r.headers.get("Content-Type") or "")
    assert "<svg" in r.get_data(as_text=True)


@pytest.mark.skipif(Flask is None, reason="flask not available")
def test_homekit_llm_context(monkeypatch, tmp_path):
    monkeypatch.setenv(
        "PILOTSUITE_HOMEKIT_SERVERS_PATH",
        str(tmp_path / "homekit_zone_servers.json"),
    )
    monkeypatch.setattr(hub_api, "_zone_engine", _FakeZoneEngine())
    homekit_api._CACHE = None
    homekit_api._RESOLVED_STORE_PATH = None

    app = _build_app_with_store()
    client = app.test_client()
    client.get("/api/v1/homekit/servers")

    context = homekit_api.get_homekit_context_for_llm()
    assert context.startswith("HomeKit-Bridge:")
    assert "Wohnbereich" in context
