"""Camera Security Engine — Slice 50."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class SecurityLevel(Enum):
    """Security level for zones."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(Enum):
    """Types of security alerts."""
    MOTION_DETECTED = "motion_detected"
    PERSON_DETECTED = "person_detected"
    VEHICLE_DETECTED = "vehicle_detected"
    SOUND_DETECTED = "sound_detected"
    DOORBELL_PRESSED = "doorbell_pressed"
    PACKAGE_DETECTED = "package_detected"
    GLASS_BREAK_DETECTED = "glass_break_detected"
    SMOKE_DETECTED = "smoke_detected"
    CO_DETECTED = "co_detected"
    WATER_LEAK_DETECTED = "water_leak_detected"


class AlertSeverity(Enum):
    """Severity levels for alerts."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class CameraConfig:
    """Camera configuration."""
    camera_id: str
    name: str
    zone_id: str
    entity_id: str
    enabled: bool = True
    motion_sensitivity: float = 0.5
    person_detection_enabled: bool = True
    package_detection_enabled: bool = False
    recording_enabled: bool = True
    snapshot_on_motion: bool = True
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "camera_id": self.camera_id,
            "name": self.name,
            "zone_id": self.zone_id,
            "entity_id": self.entity_id,
            "enabled": self.enabled,
            "motion_sensitivity": self.motion_sensitivity,
            "person_detection_enabled": self.person_detection_enabled,
            "package_detection_enabled": self.package_detection_enabled,
            "recording_enabled": self.recording_enabled,
            "snapshot_on_motion": self.snapshot_on_motion,
            "created_at": self.created_at,
        }


@dataclass
class SecurityAlert:
    """Security alert generated by camera."""
    alert_id: str
    alert_type: AlertType
    severity: AlertSeverity
    camera_id: str
    zone_id: str
    description: str
    confidence: Optional[float] = None
    snapshot_url: Optional[str] = None
    recording_url: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False
    acknowledged_at: Optional[str] = None
    acknowledged_by: Optional[str] = None
    resolved: bool = False
    resolved_at: Optional[str] = None
    resolved_by: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "alert_id": self.alert_id,
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "camera_id": self.camera_id,
            "zone_id": self.zone_id,
            "description": self.description,
            "confidence": self.confidence,
            "snapshot_url": self.snapshot_url,
            "recording_url": self.recording_url,
            "metadata": self.metadata,
            "acknowledged": self.acknowledged,
            "acknowledged_at": self.acknowledged_at,
            "acknowledged_by": self.acknowledged_by,
            "resolved": self.resolved,
            "resolved_at": self.resolved_at,
            "resolved_by": self.resolved_by,
            "created_at": self.created_at,
        }


@dataclass
class SecuritySnapshot:
    """Snapshot captured by camera."""
    snapshot_id: str
    camera_id: str
    zone_id: str
    image_url: str
    motion_detected: bool = False
    person_detected: bool = False
    package_detected: bool = False
    thumbnail_url: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "snapshot_id": self.snapshot_id,
            "camera_id": self.camera_id,
            "zone_id": self.zone_id,
            "image_url": self.image_url,
            "motion_detected": self.motion_detected,
            "person_detected": self.person_detected,
            "package_detected": self.package_detected,
            "thumbnail_url": self.thumbnail_url,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }


class CameraSecurityEngine:
    """Engine for camera-based security monitoring."""

    def __init__(
        self,
        motion_cooldown_seconds: int = 0,
        person_confidence_threshold: float = 0.7,
        auto_elevate_security_on_motion: bool = True,
        security_elevation_duration_seconds: int = 300,
    ):
        """Initialize the security engine.

        Args:
            motion_cooldown_seconds: Cooldown between motion alerts per camera (0 = no cooldown)
            person_confidence_threshold: Minimum confidence for person detection alerts
            auto_elevate_security_on_motion: Whether to elevate zone security on motion
            security_elevation_duration_seconds: How long elevated security lasts
        """
        self._cameras: Dict[str, CameraConfig] = {}
        self._alerts: Dict[str, SecurityAlert] = {}
        self._snapshots: Dict[str, SecuritySnapshot] = {}
        self._motion_last_alert: Dict[str, datetime] = {}
        self._zone_security_levels: Dict[str, SecurityLevel] = {}
        self._zone_security_elevated_at: Dict[str, datetime] = {}

        self._motion_cooldown_seconds = motion_cooldown_seconds
        self._person_confidence_threshold = person_confidence_threshold
        self._auto_elevate_security_on_motion = auto_elevate_security_on_motion
        self._security_elevation_duration_seconds = security_elevation_duration_seconds

    def register_camera(self, config: Dict[str, Any]) -> str:
        """Register a camera with the security engine.

        Args:
            config: Camera configuration dict

        Returns:
            Camera ID
        """
        camera_id = config.get("camera_id") or f"cam-{uuid.uuid4().hex[:8]}"

        camera_config = CameraConfig(
            camera_id=camera_id,
            name=config.get("name", "Unknown Camera"),
            zone_id=config.get("zone_id", "unknown"),
            entity_id=config.get("entity_id", ""),
            enabled=config.get("enabled", True),
            motion_sensitivity=config.get("motion_sensitivity", 0.5),
            person_detection_enabled=config.get("person_detection_enabled", True),
            package_detection_enabled=config.get("package_detection_enabled", False),
            recording_enabled=config.get("recording_enabled", True),
            snapshot_on_motion=config.get("snapshot_on_motion", True),
        )

        self._cameras[camera_id] = camera_config

        # Initialize zone security level if not exists
        if camera_config.zone_id not in self._zone_security_levels:
            self._zone_security_levels[camera_config.zone_id] = SecurityLevel.MEDIUM

        return camera_id

    def unregister_camera(self, camera_id: str) -> bool:
        """Unregister a camera.

        Args:
            camera_id: Camera ID to unregister

        Returns:
            True if camera was unregistered, False if not found
        """
        if camera_id in self._cameras:
            del self._cameras[camera_id]
            return True
        return False

    def get_camera(self, camera_id: str) -> Optional[Dict[str, Any]]:
        """Get camera configuration.

        Args:
            camera_id: Camera ID

        Returns:
            Camera config dict or None
        """
        camera = self._cameras.get(camera_id)
        return camera.to_dict() if camera else None

    def get_cameras(self, zone_id: Optional[str] = None, enabled_only: bool = False) -> List[Dict[str, Any]]:
        """Get list of cameras.

        Args:
            zone_id: Optional zone filter
            enabled_only: Only return enabled cameras

        Returns:
            List of camera configs
        """
        cameras = list(self._cameras.values())

        if zone_id:
            cameras = [c for c in cameras if c.zone_id == zone_id]

        if enabled_only:
            cameras = [c for c in cameras if c.enabled]

        return [c.to_dict() for c in cameras]

    def process_motion_event(
        self,
        camera_id: str,
        motion_detected: bool,
        confidence: Optional[float] = None,
    ) -> Optional[Dict[str, Any]]:
        """Process a motion detection event.

        Args:
            camera_id: Camera ID
            motion_detected: Whether motion was detected
            confidence: Optional confidence score

        Returns:
            Alert dict if created, None if suppressed or disabled
        """
        camera = self._cameras.get(camera_id)
        if not camera or not camera.enabled:
            return None

        now = datetime.now(timezone.utc)

        # Check cooldown
        last_alert = self._motion_last_alert.get(camera_id)
        if last_alert:
            elapsed = (now - last_alert).total_seconds()
            if elapsed < self._motion_cooldown_seconds:
                return None

        # Create snapshot
        snapshot = SecuritySnapshot(
            snapshot_id=f"snapshot-{uuid.uuid4().hex[:8]}",
            camera_id=camera_id,
            zone_id=camera.zone_id,
            image_url=f"/api/camera/{camera_id}/snapshot/{now.timestamp()}",
            motion_detected=True,
        )
        self._snapshots[snapshot.snapshot_id] = snapshot

        # Create alert
        alert = SecurityAlert(
            alert_id=f"alert-{uuid.uuid4().hex[:8]}",
            alert_type=AlertType.MOTION_DETECTED,
            severity=AlertSeverity.INFO,
            camera_id=camera_id,
            zone_id=camera.zone_id,
            description=f"Motion detected by {camera.name}",
            confidence=confidence,
            snapshot_url=snapshot.image_url,
        )
        self._alerts[alert.alert_id] = alert
        self._motion_last_alert[camera_id] = now

        # Auto-elevate security level
        if self._auto_elevate_security_on_motion:
            self._elevate_zone_security(camera.zone_id)

        return alert.to_dict()

    def process_person_detection(
        self,
        camera_id: str,
        confidence: float,
    ) -> Optional[Dict[str, Any]]:
        """Process a person detection event.

        Args:
            camera_id: Camera ID
            confidence: Detection confidence (0-1)

        Returns:
            Alert dict if created, None if suppressed or disabled
        """
        camera = self._cameras.get(camera_id)
        if not camera or not camera.enabled or not camera.person_detection_enabled:
            return None

        # Determine severity based on confidence
        if confidence >= self._person_confidence_threshold:
            severity = AlertSeverity.WARNING
        else:
            severity = AlertSeverity.INFO

        # Create snapshot
        snapshot = SecuritySnapshot(
            snapshot_id=f"snapshot-{uuid.uuid4().hex[:8]}",
            camera_id=camera_id,
            zone_id=camera.zone_id,
            image_url=f"/api/camera/{camera_id}/snapshot/{datetime.now(timezone.utc).timestamp()}",
            person_detected=True,
            metadata={"confidence": confidence},
        )
        self._snapshots[snapshot.snapshot_id] = snapshot

        # Create alert
        alert = SecurityAlert(
            alert_id=f"alert-{uuid.uuid4().hex[:8]}",
            alert_type=AlertType.PERSON_DETECTED,
            severity=severity,
            camera_id=camera_id,
            zone_id=camera.zone_id,
            description=f"Person detected by {camera.name} (confidence: {confidence:.0%})",
            confidence=confidence,
            snapshot_url=snapshot.image_url,
        )
        self._alerts[alert.alert_id] = alert

        # Auto-elevate security level
        if self._auto_elevate_security_on_motion:
            self._elevate_zone_security(camera.zone_id)

        return alert.to_dict()

    def process_package_detection(
        self,
        camera_id: str,
        confidence: Optional[float] = None,
    ) -> Optional[Dict[str, Any]]:
        """Process a package detection event.

        Args:
            camera_id: Camera ID
            confidence: Optional detection confidence

        Returns:
            Alert dict if created, None if suppressed or disabled
        """
        camera = self._cameras.get(camera_id)
        if not camera or not camera.enabled or not camera.package_detection_enabled:
            return None

        # Create snapshot
        snapshot = SecuritySnapshot(
            snapshot_id=f"snapshot-{uuid.uuid4().hex[:8]}",
            camera_id=camera_id,
            zone_id=camera.zone_id,
            image_url=f"/api/camera/{camera_id}/snapshot/{datetime.now(timezone.utc).timestamp()}",
            package_detected=True,
            metadata={"confidence": confidence} if confidence else {},
        )
        self._snapshots[snapshot.snapshot_id] = snapshot

        # Create alert
        alert = SecurityAlert(
            alert_id=f"alert-{uuid.uuid4().hex[:8]}",
            alert_type=AlertType.PACKAGE_DETECTED,
            severity=AlertSeverity.INFO,
            camera_id=camera_id,
            zone_id=camera.zone_id,
            description=f"Package detected by {camera.name}",
            confidence=confidence,
            snapshot_url=snapshot.image_url,
        )
        self._alerts[alert.alert_id] = alert

        return alert.to_dict()

    def acknowledge_alert(
        self,
        alert_id: str,
        acknowledged_by: Optional[str] = None,
    ) -> bool:
        """Acknowledge an alert.

        Args:
            alert_id: Alert ID
            acknowledged_by: Optional user ID who acknowledged

        Returns:
            True if acknowledged, False if not found
        """
        alert = self._alerts.get(alert_id)
        if not alert:
            return False

        alert.acknowledged = True
        alert.acknowledged_at = datetime.now(timezone.utc).isoformat()
        alert.acknowledged_by = acknowledged_by

        return True

    def resolve_alert(
        self,
        alert_id: str,
        resolved_by: Optional[str] = None,
    ) -> bool:
        """Resolve an alert.

        Args:
            alert_id: Alert ID
            resolved_by: Optional user ID who resolved

        Returns:
            True if resolved, False if not found
        """
        alert = self._alerts.get(alert_id)
        if not alert:
            return False

        alert.resolved = True
        alert.resolved_at = datetime.now(timezone.utc).isoformat()
        alert.resolved_by = resolved_by

        return True

    def get_alerts(
        self,
        unresolved_only: bool = False,
        zone_id: Optional[str] = None,
        camera_id: Optional[str] = None,
        alert_type: Optional[AlertType] = None,
        severity: Optional[AlertSeverity] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """Get alerts with optional filters.

        Args:
            unresolved_only: Only return unresolved alerts
            zone_id: Filter by zone
            camera_id: Filter by camera
            alert_type: Filter by alert type
            severity: Filter by severity
            limit: Maximum number of alerts to return

        Returns:
            List of alert dicts sorted by created_at (newest first)
        """
        alerts = list(self._alerts.values())

        if unresolved_only:
            alerts = [a for a in alerts if not a.resolved]

        if zone_id:
            alerts = [a for a in alerts if a.zone_id == zone_id]

        if camera_id:
            alerts = [a for a in alerts if a.camera_id == camera_id]

        if alert_type:
            alerts = [a for a in alerts if a.alert_type == alert_type]

        if severity:
            alerts = [a for a in alerts if a.severity == severity]

        # Sort by created_at descending
        alerts.sort(key=lambda a: a.created_at, reverse=True)

        return [a.to_dict() for a in alerts[:limit]]

    def get_snapshots(
        self,
        zone_id: Optional[str] = None,
        camera_id: Optional[str] = None,
        motion_only: bool = False,
        person_only: bool = False,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """Get snapshots with optional filters.

        Args:
            zone_id: Filter by zone
            camera_id: Filter by camera
            motion_only: Only return motion snapshots
            person_only: Only return person snapshots
            limit: Maximum number of snapshots to return

        Returns:
            List of snapshot dicts sorted by created_at (newest first)
        """
        snapshots = list(self._snapshots.values())

        if zone_id:
            snapshots = [s for s in snapshots if s.zone_id == zone_id]

        if camera_id:
            snapshots = [s for s in snapshots if s.camera_id == camera_id]

        if motion_only:
            snapshots = [s for s in snapshots if s.motion_detected]

        if person_only:
            snapshots = [s for s in snapshots if s.person_detected]

        # Sort by created_at descending
        snapshots.sort(key=lambda s: s.created_at, reverse=True)

        return [s.to_dict() for s in snapshots[:limit]]

    def get_zone_security_level(self, zone_id: str) -> SecurityLevel:
        """Get current security level for a zone.

        Args:
            zone_id: Zone ID

        Returns:
            Current security level
        """
        # Check if elevated security has expired
        elevated_at = self._zone_security_elevated_at.get(zone_id)
        if elevated_at:
            elapsed = (datetime.now(timezone.utc) - elevated_at).total_seconds()
            if elapsed >= self._security_elevation_duration_seconds:
                # Reset to MEDIUM
                self._zone_security_levels[zone_id] = SecurityLevel.MEDIUM
                del self._zone_security_elevated_at[zone_id]

        return self._zone_security_levels.get(zone_id, SecurityLevel.MEDIUM)

    def set_zone_security_level(
        self,
        zone_id: str,
        level: SecurityLevel,
    ) -> None:
        """Set security level for a zone.

        Args:
            zone_id: Zone ID
            level: Security level to set
        """
        self._zone_security_levels[zone_id] = level

        # Clear elevation timestamp if setting to MEDIUM or lower
        if level in (SecurityLevel.LOW, SecurityLevel.MEDIUM):
            self._zone_security_elevated_at.pop(zone_id, None)

    def _elevate_zone_security(self, zone_id: str) -> None:
        """Elevate security level for a zone.

        Args:
            zone_id: Zone ID
        """
        current_level = self._zone_security_levels.get(zone_id, SecurityLevel.MEDIUM)

        # Only elevate if not already at HIGH or CRITICAL
        if current_level not in (SecurityLevel.HIGH, SecurityLevel.CRITICAL):
            self._zone_security_levels[zone_id] = SecurityLevel.HIGH
            self._zone_security_elevated_at[zone_id] = datetime.now(timezone.utc)

    def get_security_summary(self) -> Dict[str, Any]:
        """Get overall security summary.

        Returns:
            Summary dict with camera/alert statistics
        """
        total_cameras = len(self._cameras)
        active_cameras = len([c for c in self._cameras.values() if c.enabled])

        total_alerts = len(self._alerts)
        unresolved_alerts = len([a for a in self._alerts.values() if not a.resolved])
        acknowledged_alerts = len([a for a in self._alerts.values() if a.acknowledged])

        zones_monitored = len(set(c.zone_id for c in self._cameras.values()))

        # Count alerts by severity
        alerts_by_severity: Dict[str, int] = {}
        for alert in self._alerts.values():
            key = alert.severity.value
            alerts_by_severity[key] = alerts_by_severity.get(key, 0) + 1

        # Count alerts by type
        alerts_by_type: Dict[str, int] = {}
        for alert in self._alerts.values():
            key = alert.alert_type.value
            alerts_by_type[key] = alerts_by_type.get(key, 0) + 1

        return {
            "total_cameras": total_cameras,
            "active_cameras": active_cameras,
            "total_alerts": total_alerts,
            "unresolved_alerts": unresolved_alerts,
            "acknowledged_alerts": acknowledged_alerts,
            "zones_monitored": zones_monitored,
            "alerts_by_severity": alerts_by_severity,
            "alerts_by_type": alerts_by_type,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }


def create_camera_security_engine(
    motion_cooldown_seconds: int = 30,
    person_confidence_threshold: float = 0.7,
    auto_elevate_security_on_motion: bool = True,
    security_elevation_duration_seconds: int = 300,
) -> CameraSecurityEngine:
    """Factory function to create a camera security engine.

    Args:
        motion_cooldown_seconds: Cooldown between motion alerts
        person_confidence_threshold: Minimum confidence for person alerts
        auto_elevate_security_on_motion: Auto-elevate on motion
        security_elevation_duration_seconds: Duration of elevated security

    Returns:
        Configured CameraSecurityEngine instance
    """
    return CameraSecurityEngine(
        motion_cooldown_seconds=motion_cooldown_seconds,
        person_confidence_threshold=person_confidence_threshold,
        auto_elevate_security_on_motion=auto_elevate_security_on_motion,
        security_elevation_duration_seconds=security_elevation_duration_seconds,
    )
