build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:latest
  aarch64: ghcr.io/home-assistant/aarch64-base-python:latest
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
